In [80]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
from sklearn.model_selection import train_test_split
import tensorflow as tf
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/gender_submission.csv
/kaggle/input/titanic/test.csv


In [81]:
train=pd.read_csv("/kaggle/input/titanic/train.csv")
test=pd.read_csv("/kaggle/input/titanic/test.csv")
print(train.head())



   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [82]:
print(test.head())


   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S  


In [83]:
y_train=train.Survived
x_train=train.drop('Survived',axis=1)

features=['Pclass','Sex','Age','SibSp','Fare']
x_train=x_train[features]
test=test[features]
print(x_train.head())
print(test.head())

   Pclass     Sex   Age  SibSp     Fare
0       3    male  22.0      1   7.2500
1       1  female  38.0      1  71.2833
2       3  female  26.0      0   7.9250
3       1  female  35.0      1  53.1000
4       3    male  35.0      0   8.0500
   Pclass     Sex   Age  SibSp     Fare
0       3    male  34.5      0   7.8292
1       3  female  47.0      1   7.0000
2       2    male  62.0      0   9.6875
3       3    male  27.0      0   8.6625
4       3  female  22.0      1  12.2875


In [84]:
x_train.Sex[x_train.Sex == 'male'] = 1
x_train.Sex[x_train.Sex == 'female'] = 2
test.Sex[test.Sex == 'male'] = 1
test.Sex[test.Sex == 'female'] = 2
print(x_train.head())
print(test.head())
x_train=x_train.fillna(0)
test=test.fillna(0)

pd.isnull(test)

   Pclass Sex   Age  SibSp     Fare
0       3   1  22.0      1   7.2500
1       1   2  38.0      1  71.2833
2       3   2  26.0      0   7.9250
3       1   2  35.0      1  53.1000
4       3   1  35.0      0   8.0500
   Pclass Sex   Age  SibSp     Fare
0       3   1  34.5      0   7.8292
1       3   2  47.0      1   7.0000
2       2   1  62.0      0   9.6875
3       3   1  27.0      0   8.6625
4       3   2  22.0      1  12.2875


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


Pclass    Sex    Age  SibSp   Fare
0     False  False  False  False  False
1     False  False  False  False  False
2     False  False  False  False  False
3     False  False  False  False  False
4     False  False  False  False  False
..      ...    ...    ...    ...    ...
413   False  False  False  False  False
414   False  False  False  False  False
415   False  False  False  False  False
416   False  False  False  False  False
417   False  False  False  False  False

[418 rows x 5 columns]

In [85]:
x_train=x_train.values

test=test.values



In [86]:

print(test)

[[ 3.      1.     34.5     0.      7.8292]
 [ 3.      2.     47.      1.      7.    ]
 [ 2.      1.     62.      0.      9.6875]
 ...
 [ 3.      1.     38.5     0.      7.25  ]
 [ 3.      1.      0.      0.      8.05  ]
 [ 3.      1.      0.      1.     22.3583]]


In [87]:
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.2,shuffle=True)
x_train=x_train.astype('float32')
y_train=y_train.astype('float32')
x_val=x_val.astype('float32')
y_val=y_val.astype('float32')
test=test.astype('float32')

tf.convert_to_tensor(x_train)
tf.convert_to_tensor(y_train)
tf.convert_to_tensor(x_val)
tf.convert_to_tensor(y_val)
tf.convert_to_tensor(test)



<tf.Tensor: shape=(418, 5), dtype=float32, numpy=
array([[ 3.    ,  1.    , 34.5   ,  0.    ,  7.8292],
       [ 3.    ,  2.    , 47.    ,  1.    ,  7.    ],
       [ 2.    ,  1.    , 62.    ,  0.    ,  9.6875],
       ...,
       [ 3.    ,  1.    , 38.5   ,  0.    ,  7.25  ],
       [ 3.    ,  1.    ,  0.    ,  0.    ,  8.05  ],
       [ 3.    ,  1.    ,  0.    ,  1.    , 22.3583]], dtype=float32)>

In [88]:
print(x_train.shape,x_val.shape)

(712, 5) (179, 5)


In [89]:
model = tf.keras.Sequential()

batch_size = 16
epochs = 100

model.add(tf.keras.layers.Dense(64, activation="relu",kernel_initializer=tf.keras.initializers.GlorotNormal(seed=1), input_shape=(None,5)))
model.add(tf.keras.layers.Dense(32, activation="relu",kernel_regularizer=tf.keras.regularizers.l1_l2(l1=1e-5, l2=1e-4)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(16, activation="tanh",kernel_initializer=tf.keras.initializers.GlorotNormal(seed=1)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(8, activation="tanh",kernel_initializer=tf.keras.initializers.GlorotNormal(seed=1)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))




model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.001,clipvalue=5),loss='binary_crossentropy',metrics=['accuracy'])

In [90]:
history=model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(x_val,y_val))

Epoch 1/100
45/45 [==============================] - 0s 6ms/step - loss: 0.7043 - accuracy: 0.5927 - val_loss: 0.6346 - val_accuracy: 0.6369
Epoch 2/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6959 - accuracy: 0.6096 - val_loss: 0.6202 - val_accuracy: 0.6872
Epoch 3/100
45/45 [==============================] - 0s 4ms/step - loss: 0.6746 - accuracy: 0.6180 - val_loss: 0.6289 - val_accuracy: 0.6816
Epoch 4/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6635 - accuracy: 0.6404 - val_loss: 0.6099 - val_accuracy: 0.6872
Epoch 5/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6484 - accuracy: 0.6643 - val_loss: 0.6204 - val_accuracy: 0.6816
Epoch 6/100
45/45 [==============================] - 0s 4ms/step - loss: 0.6541 - accuracy: 0.6531 - val_loss: 0.6103 - val_accuracy: 0.6816
Epoch 7/100
45/45 [==============================] - 0s 4ms/step - loss: 0.6432 - accuracy: 0.6517 - val_loss: 0.6024 - val_accuracy: 0.6927
Epoch 8/100
4

Epoch 59/100
45/45 [==============================] - 0s 3ms/step - loss: 0.5187 - accuracy: 0.7753 - val_loss: 0.4644 - val_accuracy: 0.7989
Epoch 60/100
45/45 [==============================] - 0s 3ms/step - loss: 0.4873 - accuracy: 0.7837 - val_loss: 0.4589 - val_accuracy: 0.8156
Epoch 61/100
45/45 [==============================] - 0s 3ms/step - loss: 0.5054 - accuracy: 0.7711 - val_loss: 0.4769 - val_accuracy: 0.8045
Epoch 62/100
45/45 [==============================] - 0s 3ms/step - loss: 0.5020 - accuracy: 0.7781 - val_loss: 0.4624 - val_accuracy: 0.8045
Epoch 63/100
45/45 [==============================] - 0s 3ms/step - loss: 0.4893 - accuracy: 0.7739 - val_loss: 0.4686 - val_accuracy: 0.7989
Epoch 64/100
45/45 [==============================] - 0s 3ms/step - loss: 0.5027 - accuracy: 0.7865 - val_loss: 0.5002 - val_accuracy: 0.7765
Epoch 65/100
45/45 [==============================] - 0s 3ms/step - loss: 0.4991 - accuracy: 0.7795 - val_loss: 0.4822 - val_accuracy: 0.7989
Epoch 

In [94]:
y=model.predict(test)


for i in range(0,len(y)):
    if y[i]<0.5:
        y[i]=0
    else:
        y[i]=1
print(y)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

In [ ]:
Submission = pd.DataFrame({ 'PassengerId': PassengerID,
                            'Survived': predictions })
Submission.to_csv("Submission.csv", index=False)